# This notebook demonstrates the basics of Julia!

In [1]:
println("Hello world!")

Hello world!


In [2]:
variable = 42 
typeof(variable)

Int64

** You don't have to type your variables in Julia... but you can if you want. Here are some common math expressions ** 

In [3]:
sum = 3+7

10

In [4]:
difference = 10-3

7

In [5]:
product = 20*5

100

In [6]:
quotient = 100/10

10.0

In [7]:
power = 10 ^ 2 

100

In [8]:
modulus = 101%2

1

# Here are some examples of strings 

In [9]:
# enclose characters in "" or """ """ 

sl = "I am a string" 
println(sl)

I am a string


In [10]:
test_string = """Look, Mom, no "errors"!!! """ 
println(test_string) 

Look, Mom, no "errors"!!! 


In [11]:
#NOTE: characters are enclosed by single quotation marks 
name = "John" 
Birthday = "3-14-1997"

println("My name is $(name). I was born on $(Birthday)")

My name is John. I was born on 3-14-1997


# Dictionaries, tuples, and arrays 

In [12]:
dictionary = Dict("name" => "John", "age"=>21)
println(dictionary["name"])
println(dictionary["age"])

John
21


In [13]:
# add another entry 
dictionary["eyes"] = "blue"

println(dictionary["eyes"])

blue


# LOOPS  

In [31]:
# note that while loops are local in scope

i = 1; 
while i < 10
    println(i) 
    global i += 1 
end

# this is kind of funky and will require some careful thought later

1
2
3
4
5
6
7
8
9


In [32]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


** We can replace the in with either = or ∈ ** 

In [33]:
for i = 1:10
    println(i)
end


1
2
3
4
5
6
7
8
9
10


In [34]:
for i ∈ 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [35]:
m, n = 5, 5 
A = zeros(m, n) 

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [40]:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

** Condense a nested for loop ** 

In [41]:
for i in 1:m, j in 1:n 
    A[i, j] = i*j
end
A

5×5 Array{Float64,2}:
 1.0   2.0   3.0   4.0   5.0
 2.0   4.0   6.0   8.0  10.0
 3.0   6.0   9.0  12.0  15.0
 4.0   8.0  12.0  16.0  20.0
 5.0  10.0  15.0  20.0  25.0

**Do the same thing with comprehension ** 

In [53]:
A = [i - j for i in 1:m, j in 1:n]
display(A)
# display seems to be a nice way to print matrices

5×5 Array{Int64,2}:
 0  -1  -2  -3  -4
 1   0  -1  -2  -3
 2   1   0  -1  -2
 3   2   1   0  -1
 4   3   2   1   0

In [54]:
?display()

```
display(x)
display(d::AbstractDisplay, x)
display(mime, x)
display(d::AbstractDisplay, mime, x)
```

AbstractDisplay `x` using the topmost applicable display in the display stack, typically using the richest supported multimedia output for `x`, with plain-text [`stdout`](@ref) output as a fallback. The `display(d, x)` variant attempts to display `x` on the given display `d` only, throwing a [`MethodError`](@ref) if `d` cannot display objects of this type.

In general, you cannot assume that `display` output goes to `stdout` (unlike [`print(x)`](@ref) or [`show(x)`](@ref)).  For example, `display(x)` may open up a separate window with an image. `display(x)` means "show `x` in the best way you can for the current output device(s)." If you want REPL-like text output that is guaranteed to go to `stdout`, use [`show(stdout, "text/plain", x)`](@ref) instead.

There are also two variants with a `mime` argument (a MIME type string, such as `"image/png"`), which attempt to display `x` using the requested MIME type *only*, throwing a `MethodError` if this type is not supported by either the display(s) or by `x`. With these variants, one can also supply the "raw" data in the requested MIME type by passing `x::AbstractString` (for MIME types with text-based storage, such as text/html or application/postscript) or `x::Vector{UInt8}` (for binary MIME types).


# Conditionals

In [56]:
x = 12 ;
y = 90 ;

In [57]:
if x > y
    println("$x is larger than $y")
elseif y > x 
    println("$y is larger than $x") 
else
    println("$x and $y are equal")
end

90 is larger than 12


# Functions

In [58]:
function sayhi(name)
    println("Hi $name, it's great to see you!")
end

sayhi (generic function with 1 method)

In [70]:
function f(x)
    return x^2
end

f (generic function with 1 method)

In [71]:
sayhi("C-3PO")

Hi C-3PO, it's great to see you!


In [72]:
x = 42 
println(f(x))
println(x)

1764
42


In [76]:
g(x) = x^2  # we can define one line functions just like in math

g (generic function with 1 method)

In [77]:
println(g(42))

1764


In [ ]:
# anonymous / lambda function

In [79]:
f3 = x -> x^2  # think of this like a mapping 

#15 (generic function with 1 method)

In [80]:
f3(42)

1764

## Duck-typing in Julia

In [81]:
sayhi(555666)

Hi 555666, it's great to see you!


In [83]:
A = rand(3,3) 
display(A)

3×3 Array{Float64,2}:
 0.226886  0.309842  0.439464
 0.354424  0.536131  0.794543
 0.735407  0.146243  0.37267 

In [85]:
f(A)

3×3 Array{Float64,2}:
 0.484477  0.300684  0.509666
 0.854744  0.513448  0.877838
 0.492749  0.360766  0.578264

In [86]:
v = rand(3) # vector squaring will not make sense (outer vs inner product)

3-element Array{Float64,1}:
 0.6000610970559004
 0.7310635456972869
 0.3096321466430898

In [87]:
f(v)

LoadError: MethodError: no method matching ^(::Array{Float64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Float16, ::Integer) at math.jl:782
  ^(!Matched::Missing, ::Integer) at missing.jl:120
  ^(!Matched::Missing, ::Number) at missing.jl:93
  ...

** If you want your functions to be able to change a variable (like pass by reference) then add a bang ! after the name ** 

In [92]:
x = [12, 11, 10]
sort!(x)
println(x)

[10, 11, 12]


** To make a function broadcast element-wise use the . ** 

In [94]:
x = rand(3)
println(x)
println(f.(x))

[0.168573, 0.0347505, 0.170214]
[0.028417, 0.0012076, 0.0289727]


Hello world!
